const londonLocations = [
  "Greater London",
  "Central London",
  "North London",
  "East London",
  "South London",
  "West London",
  "City of London",
  "Westminster",
  "Camden",
  "Islington",
  "Hackney",
  "Tower Hamlets",
  "Southwark",
  "Lambeth",
  "Wandsworth",
  "Hammersmith and Fulham",
  "Kensington and Chelsea",
  "Brent",
  "Ealing",
  "Hounslow",
  "Richmond upon Thames",
  "Kingston upon Thames",
  "Merton",
  "Sutton",
  "Croydon",
  "Bromley",
  "Lewisham",
  "Greenwich",
  "Bexley",
  "Havering",
  "Barking and Dagenham",
  "Redbridge",
  "Newham",
  "Waltham Forest",
  "Haringey",
  "Enfield",
  "Barnet",
  "Harrow",
  "Hillingdon"
];

export default londonLocations;